sudo: required
services:
  - docker

before_install:
  - docker build -t docker-course/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-course/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test3"
  env: "Test3-env"
  bucket_name: "elasticbeanstalk-us-east-1-626561479647"
  bucket_path: "test3"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"